spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssm?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    password: Zcjlq310.
    username: root
  session:
    store-type: none
security:
  basic:
    enabled: false
server:
  port: 8090
#ssm:
#  security:
#    browser:
#      loginType: JSON
#    code:
#      image:
#        length: 5
#        width: 80
#        url: /user,/user/*

